/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClienteIndexRouteImport } from './routes/_authenticated/cliente.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedClientePerfilRouteImport } from './routes/_authenticated/cliente.perfil'
import { Route as AuthenticatedClienteNotificacoesRouteImport } from './routes/_authenticated/cliente.notificacoes'
import { Route as AuthenticatedClienteEvolucaoRouteImport } from './routes/_authenticated/cliente.evolucao'
import { Route as AuthenticatedClienteCronogramaRouteImport } from './routes/_authenticated/cliente.cronograma'
import { Route as AuthenticatedClienteAnamneseRouteImport } from './routes/_authenticated/cliente.anamnese'
import { Route as AuthenticatedClienteAgendamentosRouteImport } from './routes/_authenticated/cliente.agendamentos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminServicosRouteImport } from './routes/_authenticated/admin.servicos'
import { Route as AuthenticatedAdminProfissionaisRouteImport } from './routes/_authenticated/admin.profissionais'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminBloqueiosRouteImport } from './routes/_authenticated/admin.bloqueios'
import { Route as AuthenticatedAdminAgendamentosRouteImport } from './routes/_authenticated/admin.agendamentos'
import { Route as AuthenticatedAdminAgendaRouteImport } from './routes/_authenticated/admin.agenda'
import { Route as AuthenticatedAdminClientesIdRouteImport } from './routes/_authenticated/admin.clientes.$id'
import { Route as AuthenticatedAdminClientesIdCronogramaRouteImport } from './routes/_authenticated/admin.clientes.$id.cronograma'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteIndexRoute =
  AuthenticatedClienteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedClientePerfilRoute =
  AuthenticatedClientePerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteNotificacoesRoute =
  AuthenticatedClienteNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteEvolucaoRoute =
  AuthenticatedClienteEvolucaoRouteImport.update({
    id: '/evolucao',
    path: '/evolucao',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteCronogramaRoute =
  AuthenticatedClienteCronogramaRouteImport.update({
    id: '/cronograma',
    path: '/cronograma',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteAnamneseRoute =
  AuthenticatedClienteAnamneseRouteImport.update({
    id: '/anamnese',
    path: '/anamnese',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteAgendamentosRoute =
  AuthenticatedClienteAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicosRoute =
  AuthenticatedAdminServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfissionaisRoute =
  AuthenticatedAdminProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBloqueiosRoute =
  AuthenticatedAdminBloqueiosRouteImport.update({
    id: '/bloqueios',
    path: '/bloqueios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgendamentosRoute =
  AuthenticatedAdminAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgendaRoute =
  AuthenticatedAdminAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesIdRoute =
  AuthenticatedAdminClientesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientesRoute,
  } as any)
const AuthenticatedAdminClientesIdCronogramaRoute =
  AuthenticatedAdminClientesIdCronogramaRouteImport.update({
    id: '/cronograma',
    path: '/cronograma',
    getParentRoute: () => AuthenticatedAdminClientesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/agendamentos': typeof AuthenticatedAdminAgendamentosRoute
  '/admin/bloqueios': typeof AuthenticatedAdminBloqueiosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/profissionais': typeof AuthenticatedAdminProfissionaisRoute
  '/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/agendamentos': typeof AuthenticatedClienteAgendamentosRoute
  '/cliente/anamnese': typeof AuthenticatedClienteAnamneseRoute
  '/cliente/cronograma': typeof AuthenticatedClienteCronogramaRoute
  '/cliente/evolucao': typeof AuthenticatedClienteEvolucaoRoute
  '/cliente/notificacoes': typeof AuthenticatedClienteNotificacoesRoute
  '/cliente/perfil': typeof AuthenticatedClientePerfilRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cliente/': typeof AuthenticatedClienteIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRouteWithChildren
  '/admin/clientes/$id/cronograma': typeof AuthenticatedAdminClientesIdCronogramaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/agendamentos': typeof AuthenticatedAdminAgendamentosRoute
  '/admin/bloqueios': typeof AuthenticatedAdminBloqueiosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/profissionais': typeof AuthenticatedAdminProfissionaisRoute
  '/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/agendamentos': typeof AuthenticatedClienteAgendamentosRoute
  '/cliente/anamnese': typeof AuthenticatedClienteAnamneseRoute
  '/cliente/cronograma': typeof AuthenticatedClienteCronogramaRoute
  '/cliente/evolucao': typeof AuthenticatedClienteEvolucaoRoute
  '/cliente/notificacoes': typeof AuthenticatedClienteNotificacoesRoute
  '/cliente/perfil': typeof AuthenticatedClientePerfilRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cliente': typeof AuthenticatedClienteIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRouteWithChildren
  '/admin/clientes/$id/cronograma': typeof AuthenticatedAdminClientesIdCronogramaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/_authenticated/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/_authenticated/admin/agendamentos': typeof AuthenticatedAdminAgendamentosRoute
  '/_authenticated/admin/bloqueios': typeof AuthenticatedAdminBloqueiosRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRouteWithChildren
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/profissionais': typeof AuthenticatedAdminProfissionaisRoute
  '/_authenticated/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/cliente/agendamentos': typeof AuthenticatedClienteAgendamentosRoute
  '/_authenticated/cliente/anamnese': typeof AuthenticatedClienteAnamneseRoute
  '/_authenticated/cliente/cronograma': typeof AuthenticatedClienteCronogramaRoute
  '/_authenticated/cliente/evolucao': typeof AuthenticatedClienteEvolucaoRoute
  '/_authenticated/cliente/notificacoes': typeof AuthenticatedClienteNotificacoesRoute
  '/_authenticated/cliente/perfil': typeof AuthenticatedClientePerfilRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cliente/': typeof AuthenticatedClienteIndexRoute
  '/_authenticated/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRouteWithChildren
  '/_authenticated/admin/clientes/$id/cronograma': typeof AuthenticatedAdminClientesIdCronogramaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/auth'
    | '/admin'
    | '/cliente'
    | '/admin/agenda'
    | '/admin/agendamentos'
    | '/admin/bloqueios'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/profissionais'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/cliente/agendamentos'
    | '/cliente/anamnese'
    | '/cliente/cronograma'
    | '/cliente/evolucao'
    | '/cliente/notificacoes'
    | '/cliente/perfil'
    | '/admin/'
    | '/cliente/'
    | '/admin/clientes/$id'
    | '/admin/clientes/$id/cronograma'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/auth'
    | '/admin/agenda'
    | '/admin/agendamentos'
    | '/admin/bloqueios'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/profissionais'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/cliente/agendamentos'
    | '/cliente/anamnese'
    | '/cliente/cronograma'
    | '/cliente/evolucao'
    | '/cliente/notificacoes'
    | '/cliente/perfil'
    | '/admin'
    | '/cliente'
    | '/admin/clientes/$id'
    | '/admin/clientes/$id/cronograma'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agendar'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/cliente'
    | '/_authenticated/admin/agenda'
    | '/_authenticated/admin/agendamentos'
    | '/_authenticated/admin/bloqueios'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/profissionais'
    | '/_authenticated/admin/servicos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/cliente/agendamentos'
    | '/_authenticated/cliente/anamnese'
    | '/_authenticated/cliente/cronograma'
    | '/_authenticated/cliente/evolucao'
    | '/_authenticated/cliente/notificacoes'
    | '/_authenticated/cliente/perfil'
    | '/_authenticated/admin/'
    | '/_authenticated/cliente/'
    | '/_authenticated/admin/clientes/$id'
    | '/_authenticated/admin/clientes/$id/cronograma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/': {
      id: '/_authenticated/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof AuthenticatedClienteIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/cliente/perfil': {
      id: '/_authenticated/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof AuthenticatedClientePerfilRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/notificacoes': {
      id: '/_authenticated/cliente/notificacoes'
      path: '/notificacoes'
      fullPath: '/cliente/notificacoes'
      preLoaderRoute: typeof AuthenticatedClienteNotificacoesRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/evolucao': {
      id: '/_authenticated/cliente/evolucao'
      path: '/evolucao'
      fullPath: '/cliente/evolucao'
      preLoaderRoute: typeof AuthenticatedClienteEvolucaoRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/cronograma': {
      id: '/_authenticated/cliente/cronograma'
      path: '/cronograma'
      fullPath: '/cliente/cronograma'
      preLoaderRoute: typeof AuthenticatedClienteCronogramaRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/anamnese': {
      id: '/_authenticated/cliente/anamnese'
      path: '/anamnese'
      fullPath: '/cliente/anamnese'
      preLoaderRoute: typeof AuthenticatedClienteAnamneseRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/agendamentos': {
      id: '/_authenticated/cliente/agendamentos'
      path: '/agendamentos'
      fullPath: '/cliente/agendamentos'
      preLoaderRoute: typeof AuthenticatedClienteAgendamentosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/servicos': {
      id: '/_authenticated/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AuthenticatedAdminServicosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profissionais': {
      id: '/_authenticated/admin/profissionais'
      path: '/profissionais'
      fullPath: '/admin/profissionais'
      preLoaderRoute: typeof AuthenticatedAdminProfissionaisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bloqueios': {
      id: '/_authenticated/admin/bloqueios'
      path: '/bloqueios'
      fullPath: '/admin/bloqueios'
      preLoaderRoute: typeof AuthenticatedAdminBloqueiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agendamentos': {
      id: '/_authenticated/admin/agendamentos'
      path: '/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AuthenticatedAdminAgendamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agenda': {
      id: '/_authenticated/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AuthenticatedAdminAgendaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes/$id': {
      id: '/_authenticated/admin/clientes/$id'
      path: '/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientesIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientesRoute
    }
    '/_authenticated/admin/clientes/$id/cronograma': {
      id: '/_authenticated/admin/clientes/$id/cronograma'
      path: '/cronograma'
      fullPath: '/admin/clientes/$id/cronograma'
      preLoaderRoute: typeof AuthenticatedAdminClientesIdCronogramaRouteImport
      parentRoute: typeof AuthenticatedAdminClientesIdRoute
    }
  }
}

interface AuthenticatedAdminClientesIdRouteChildren {
  AuthenticatedAdminClientesIdCronogramaRoute: typeof AuthenticatedAdminClientesIdCronogramaRoute
}

const AuthenticatedAdminClientesIdRouteChildren: AuthenticatedAdminClientesIdRouteChildren =
  {
    AuthenticatedAdminClientesIdCronogramaRoute:
      AuthenticatedAdminClientesIdCronogramaRoute,
  }

const AuthenticatedAdminClientesIdRouteWithChildren =
  AuthenticatedAdminClientesIdRoute._addFileChildren(
    AuthenticatedAdminClientesIdRouteChildren,
  )

interface AuthenticatedAdminClientesRouteChildren {
  AuthenticatedAdminClientesIdRoute: typeof AuthenticatedAdminClientesIdRouteWithChildren
}

const AuthenticatedAdminClientesRouteChildren: AuthenticatedAdminClientesRouteChildren =
  {
    AuthenticatedAdminClientesIdRoute:
      AuthenticatedAdminClientesIdRouteWithChildren,
  }

const AuthenticatedAdminClientesRouteWithChildren =
  AuthenticatedAdminClientesRoute._addFileChildren(
    AuthenticatedAdminClientesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgendaRoute: typeof AuthenticatedAdminAgendaRoute
  AuthenticatedAdminAgendamentosRoute: typeof AuthenticatedAdminAgendamentosRoute
  AuthenticatedAdminBloqueiosRoute: typeof AuthenticatedAdminBloqueiosRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRouteWithChildren
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminProfissionaisRoute: typeof AuthenticatedAdminProfissionaisRoute
  AuthenticatedAdminServicosRoute: typeof AuthenticatedAdminServicosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgendaRoute: AuthenticatedAdminAgendaRoute,
  AuthenticatedAdminAgendamentosRoute: AuthenticatedAdminAgendamentosRoute,
  AuthenticatedAdminBloqueiosRoute: AuthenticatedAdminBloqueiosRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRouteWithChildren,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminProfissionaisRoute: AuthenticatedAdminProfissionaisRoute,
  AuthenticatedAdminServicosRoute: AuthenticatedAdminServicosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClienteRouteChildren {
  AuthenticatedClienteAgendamentosRoute: typeof AuthenticatedClienteAgendamentosRoute
  AuthenticatedClienteAnamneseRoute: typeof AuthenticatedClienteAnamneseRoute
  AuthenticatedClienteCronogramaRoute: typeof AuthenticatedClienteCronogramaRoute
  AuthenticatedClienteEvolucaoRoute: typeof AuthenticatedClienteEvolucaoRoute
  AuthenticatedClienteNotificacoesRoute: typeof AuthenticatedClienteNotificacoesRoute
  AuthenticatedClientePerfilRoute: typeof AuthenticatedClientePerfilRoute
  AuthenticatedClienteIndexRoute: typeof AuthenticatedClienteIndexRoute
}

const AuthenticatedClienteRouteChildren: AuthenticatedClienteRouteChildren = {
  AuthenticatedClienteAgendamentosRoute: AuthenticatedClienteAgendamentosRoute,
  AuthenticatedClienteAnamneseRoute: AuthenticatedClienteAnamneseRoute,
  AuthenticatedClienteCronogramaRoute: AuthenticatedClienteCronogramaRoute,
  AuthenticatedClienteEvolucaoRoute: AuthenticatedClienteEvolucaoRoute,
  AuthenticatedClienteNotificacoesRoute: AuthenticatedClienteNotificacoesRoute,
  AuthenticatedClientePerfilRoute: AuthenticatedClientePerfilRoute,
  AuthenticatedClienteIndexRoute: AuthenticatedClienteIndexRoute,
}

const AuthenticatedClienteRouteWithChildren =
  AuthenticatedClienteRoute._addFileChildren(AuthenticatedClienteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClienteRoute: AuthenticatedClienteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgendarRoute: AgendarRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
